[package]
name = "xtask"
version = "0.1.0"
publish = false
edition = "2021"

[[bin]]
name = "xtask"

[dependencies]
anyhow = "1.0"
xshell = "0.2"
xflags = "0.2"
ureq = { version = "2.6.2", default-features = false }
quote = "1.0.23"
proc-macro2 = "1.0.51"
ucd-trie = "0.1.5"
